### PR TITLE
Revamp build process

### LINKED ISSUE #7: mini* images do not strip properly?
Happens on all mini and mini-bb image variants. Is this something that can be safely ignored?

This was suppressed/ignored by the `|| exit 0` at the end of this:
```dockerfile
# mini
RUN xbps-install -yMU binutils && \
        strip /target/usr/lib/* /target/usr/bin/* || exit 0
# mini-bb
RUN xbps-install -yMU busybox-huge binutils && \
for util in $(busybox --list) ; do [ ! -f /target/usr/bin/$util ] && ln -svf /usr/bin/busybox /target/usr/bin/$util ; done && \
strip /target/usr/lib/* /target/usr/bin/* || exit 0
```

sample of the output:
```
#7 22.46 strip: Unable to recognise the format of the input file `/target/usr/lib/ld-2.32.so'
#7 22.46 strip: Unable to recognise the format of the input file `/target/usr/lib/ld-linux-x86-64.so.2'
#7 22.46 strip: Unable to recognise the format of the input file `/target/usr/lib/libBrokenLocale-2.32.so'
#7 22.46 strip: Unable to recognise the format of the input file `/target/usr/lib/libBrokenLocale.so'
#7 22.46 strip: Unable to recognise the format of the input file `/target/usr/lib/libBrokenLocale.so.1'
#7 22.46 strip: Unable to recognise the format of the input file `/target/usr/lib/libSegFault.so'
#7 22.46 strip: Unable to recognise the format of the input file `/target/usr/lib/libacl.so.1'
#7 22.46 strip: Unable to recognise the format of the input file `/target/usr/lib/libacl.so.1.1.2301'
#7 22.46 strip: Unable to recognise the format of the input file `/target/usr/lib/libanl-2.32.so'
#7 22.46 strip: Unable to recognise the format of the input file `/target/usr/lib/libanl.so'
#7 22.46 strip: Unable to recognise the format of the input file `/target/usr/lib/libanl.so.1'
#7 22.46 strip: Unable to recognise the format of the input file `/target/usr/lib/libarchive.so.13'
#7 22.47 strip: Unable to recognise the format of the input file `/target/usr/lib/libarchive.so.13.6.0'
#7 22.47 strip: Unable to recognise the format of the input file `/target/usr/lib/libattr.so.1'
#7 22.47 strip: Unable to recognise the format of the input file `/target/usr/lib/libattr.so.1.1.2501'
#7 22.47 strip: Unable to recognise the format of the input file `/target/usr/lib/libbz2.so.1'
#7 22.47 strip: Unable to recognise the format of the input file `/target/usr/lib/libbz2.so.1.0'
#7 22.47 strip: Unable to recognise the format of the input file `/target/usr/lib/libbz2.so.1.0.8'
#7 22.47 strip: Unable to recognise the format of the input file `/target/usr/lib/libc-2.32.so'
#7 22.47 strip: /target/usr/lib/libc.so: file format not recognized
```

### LINKED ISSUE #9: mini-bb-musl tag does not support linux/arm64/v8
```shell
$ sudo docker run -it --rm ghcr.io/void-linux/void-linux:mini-bb-musl
Unable to find image 'ghcr.io/void-linux/void-linux:mini-bb-musl' locally
mini-bb-musl: Pulling from void-linux/void-linux
b8bade5013d9: Pull complete
e5991dee9f7c: Pull complete
Digest: sha256:8ec89c31ad2e377e1a126c5f07f8d3cea88a9c432fde2098f0d7abbef3c16d17
Status: Downloaded newer image for ghcr.io/void-linux/void-linux:mini-bb-musl
WARNING: The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /bin/sh: exec format error
```

### PR DESCRIPTION
**Pull request by classabbyamp**
big thanks to @Duncaen for getting this started

### Highlights

- separate image names instead of tags for variants
- uses manifests for different platforms
- unified Dockerfiles into a single Containerfile
- supports using `docker buildx bake`
- simplified CI:
  - now runs on every push
  - tags `latest` and `YYYYMMDD` on pushes to master
  - metadata is automatically generated
  - uses github actions cache for storing build cache
- adjusted `noextract.conf`

### TODOs

(not necessarily blocking)

- [x] blog post about changes (https://github.com/void-linux/void-linux.github.io/pull/215)
- [x] section on download page of the website (https://github.com/void-linux/void-linux.github.io/pull/215)
- [x] add masterdir image generation to void-packages (https://github.com/void-linux/void-packages/pull/45320)
- [ ] podman build instructions for readme?
- [ ] publish on dockerhub too?
- [ ] should images be built on pull request events too? could be nice to have some CI
- [ ] rename this repo?

fixes #7
fixes #9

### CODE REVIEW

File: setup.sh [hunk 1]
```diff
@@ -0,0 +1,29 @@
+#!/bin/sh
+
+: "${MIRROR:=https://repo-default.voidlinux.org/}"
```
Comment (the-maldridge) [inline setup.sh]: This should probably default to `repo-ci`

**Review by the-maldridge — APPROVED** [review]
